### ISSUE TITLE
Error: Cannot execute binary file

### ISSUE THREAD

**Issue by imacrayon** [MaestroError/html-strings-affixer#1]
Installed via Composer added an `affixer.json` file in my project and ran `./vendor/bin/hsa check` I get this error:

```sh                          
./vendor/bin/hsa: line 37: /Users/user/projects/project/vendor/maestroerror/html-strings-affixer/bin/hsa: cannot execute binary file
```

The file permissions look to be correct in `vendor/bin` and `vendor/maestroerror/html-strings-affixer/bin/hsa`. If I try running the script directly in `vendor/maestroerror/html-strings-affixer/bin/hsa` I get:

```sh
zsh: exec format error
```

What am I doing wrong?

**Comment by MaestroError** [comment]
Hi, @imacrayon ! Thank you for the feedback! You are doing everything right 👍 I think we have here a problem with platform. Which os are you using? MacOS?

Please provide information about your env, I will do my best to solve this issue ASAP 🚀

**Comment by imacrayon** [comment]
Sorry, forgot to mention that, yes I’m using MacOS.

**Comment by MaestroError** [comment]
@imacrayon I added new executables for MacOS and updated documentation, please check it out. 
- MacOS: `./vendor/bin/hsamac`
- MacOS arm64 (m1): `./vendor/bin/hsamacm1`

I created a new release, so you can update it to version **1.2.0** with Composer and try it on your system. Let me know if it will work for you so I will be able to close this issue 👍

**Comment by imacrayon** [comment]
`hsamac` worked for me, thanks!
