### ISSUE TITLE
@endif becomes {{ __('@endif') }}

### ISSUE THREAD

**Issue by rabol** [MaestroError/html-strings-affixer#3]
I'm using the example config

running with replace command turns

```@endif``` into ```{{ __('@endif') }}```

**Comment by rabol** [comment]
and some foreach becomes ```{{ __('@endforeach') }}```

**Comment by rabol** [comment]
@enderror becomes ``` {{ __('@enderror') }}```

**Comment by MaestroError** [comment]
Hi, @rabol! Thank you for the feedback, as it seems the example config doesn't contain the "@" character. Please just add it to the "ignore" array and your issue should be fixed 👍

**Comment by MaestroError** [comment]
I updated the example config and added a note in Docs. After I will add "@" in default ignore characters too, but for now, it needs to be specified via the "affixer.json" file. You can check out the new [example config](https://github.com/MaestroError/html-strings-affixer/blob/maestro/bin/affixer-example.json)

**Comment by MaestroError** [comment]
Added  "@" as default ignore character ✔️
