### ISSUE TITLE
Space in project path causes an error

### ISSUE THREAD

**Issue by FSElias** [MaestroError/html-strings-affixer#6]
Hi, I have a Larvel project installed in

```
D:\LVProjects\XXXXXXX Project\XXXXXXX>
```

when I run
```
vendor\bin\hsawin
```

I get this:
```
'D:\LVProjects\XXXXXXX' is not recognized as an internal or external command,
operable program or batch file.
```

Please advise, thank you.

**Comment by MaestroError** [comment]
Hi @FSElias , thank you for the feedback! I already fixed the issue, just update your version to 1.2.1 and it will work 👍
